### ISSUE TITLE
Can't unpin card unless I pin it twice

### ISSUE THREAD

**Issue by fosterphil** [TeraLogics/TotalBriecall#10]
Steps to reproduce:
1. Click pin on one of the cards
2. Card pins at the top as expected
3. When I go to unpin the card, the pin option does not display as selected so I can not unpin it
4. I select to pin the card again
4. Now I have two identical cards at the top, both of which show the pin option selected (I can now unpin both)

We should have the pin option display as selected after selecting to pin the card the first time. We should not have to pin it again.

**Comment by dbussert** [comment]
pinning has been removed

**Comment by ardoramor** [comment]
I've actually fixed that but the more global pin flow needed more work so i just removed it. Probably needed a separaed "My pinned racalls" page.
