### ISSUE TITLE
Install Instructions Feedback Round 1

### ISSUE THREAD

**Issue by rushce** [TeraLogics/TotalBriecall#4]
Started following the install steps for Heroku deployment - there were not accomodating for new users. Couple of places where steps need to be added to account for the assumption that every reader is a new user. 

I've captured specific notes here in the document at the link below. 
https://drive.google.com/open?id=0B8O-UbreVgpZdUJWNWM3Z1hMMDQ&authuser=0

I cannot go any further because I receive a permissions error that reads:

[Item could not be retrieved:
GET https://api.github.com/search/repositories?q=fork%3Atrue+user%3Arushce+teralogics: 422 - Validation Failed Error summary: message: The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them. resource: Search field: q code: invalid // See: https://developer.github.com/v3/search/]

**Comment by rushce** [comment]
I think the installation instructions would benefit from an overview paragraph. Something short detailing why you would be following these steps and what it accomplishes.

**Comment by mbell8903** [comment]
Added overview

**Comment by rushce** [comment]
The Login / Create Account section apply here? After I completed the first set of steps, I am already logged into Heroku, yet these direct me to Login - maybe these should just be steps for Creating an account, and consider adding a "*Move ahead to steps for 'Enabling CI' " after the fifth step in the "Step by step deployment instructions for Total Briecall:" which would move users who already have accounts, past these steps.

Enabling CI - I think you need to be connected to GitHub for these steps to work. Following the steps as is, I am not connected to GitHub. When I get through step 3, it looks like that is where I would need to connect to GitHub. I click this button, but when I search for the repository to connect to, I get the error message:
 Item could not be retrieved:
GET https://api.github.com/search/repositories?q=fork%3Atrue+user%3Arushce+TeraLogics%2FTotalBriecall: 422 - Validation Failed Error summary: message: The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them. resource: Search field: q code: invalid // See: https://developer.github.com/v3/search/

Some steps are missing if you are not connected to GitHub repository... unless steps are missing elsewhere that would solve for this before the Enabling CI steps....

**Comment by rushce** [comment]
For "Creating a Facebook Application ID" - the steps should be: 
1. Go to Facebook's Developers Page. 
2. In the upper left hand corner, click 'My Apps'. From the drop down menu, select "Register As a Developer" and accept the "Facebook Platform Policy" and "Facebook Privacy Policy" to proceed. Select the "My Apps" dropdown again and click "Add a New App"
   or
   If you are already registered, select "Add a New App"
3. From the Modal Dialog that comes up, select "Website" 

etc.

**Comment by dbussert** [comment]
removed facebook id due to the long turn around time

**Comment by dbussert** [comment]
Added dockers instructions and made all api keys optional
