### ISSUE TITLE
Don't make the manufacturer a clickable item, it just reloads the page

### ISSUE THREAD

**Issue by fosterphil** [TeraLogics/TotalBriecall#9]
When clicking the vendor/manufacturer name under the card title, it just reloads the page to the top.

I was expecting it to take me to the details/info page. (e.g. Empirical Laboratories, Incorporated)

**Comment by dbussert** [comment]
changing this to say make manufacturer not a clickable item.

**Comment by dbussert** [comment]
Fixed in a14b261
